repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: requirements-txt-fixer
        files: ^requirements\.txt$

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ["--severity-level", "medium", "--confidence-level", "high"]
        exclude: ^(tests|build|examples|local_setup)/
