from .polly_synthesizer import PollySynthesizer
from .elevenlabs_synthesizer import ElevenlabsSynthesizer
from .openai_synthesizer import OPENAISynthesizer
from .fourie_synthesizer import FourieSynthesizer
from .deepgram_synthesizer import DeepgramSynthesizer
from .melo_synthesizer import MeloSynthesizer
from .styletts_synthesizer import StylettsSynthesizer
from .azure_synthesizer import AzureSynthesizer